Use `ls` instead of `find` for EE ansible docs
ansible/ansible-language-server pull request #190
Opened 2022-01-26 09:20 UTC by ganeshrn

*  Currently `find` command is used to check if
   ansible plugins are present for a given candidate
   path.
*  In some cases the `findutils` might not be
   bundled within `execution-environments`.
*  Hence instead `find` command the PR updates
   logic to use `ls` command to figure out if
   ansible plugin files are present in a given path

2022-01-26 09:49 UTC, ssbarnea requested changes
The changed text is not covered by any tests so the CI result is pretty much useless in that case, testing only that the modified code compiles.

Look at https://app.codecov.io/gh/ansible/ansible-language-server/blob/main/src/services/executionEnvironment.ts

Can you please address that?

2022-01-26 10:50 UTC, ganeshrn commented
@ssbarnea As your are aware testing is very minimal for this repository and improving the test coverage is handled as part of issue https://github.com/ansible/vscode-ansible/issues/213 
This PR tries to fix a know issue with downstream EE's and not a new feature addition. So I think it's shouldn't be blocked for lack of test as it is simultaneously worked up and the issue I referenced earlier will be used to track it.

2022-01-26 13:19 UTC, cidrblock approved these changes
Thanks for this

2022-03-01 16:12 UTC, ssbarnea approved these changes

2022-03-01 16:22 UTC, merged