Reformat typescript using prettier
ansible/ansible-language-server pull request #196
Opened 2022-01-28 12:32 UTC by ssbarnea

That enables typescript on prettier as currently almost any attempt
to edit .ts files using vscode would introduce undesired reformatting.
That is because we recommend prettier extension which auto-reformats
but without checking that in CI.

The only manually made change is the one line in pre-commit config,
the rest is just pre-commit itself.

2022-01-28 12:48 UTC, ganeshrn approved these changes
Thanks!

2022-01-28 13:24 UTC, cidrblock approved these changes
I am admittedly not completely familiar with the code base, but this seems like a good idea as it will bring consistency to the repo without anyone having to lift a finger and smooth the path for future contributors.

2022-01-28 14:28 UTC, merged

2022-01-29 06:11 UTC, webknjaz requested changes

2022-01-29 06:11 UTC, webknjaz commented on .pre-commit-config.yaml
> +      - id: markdownlint
This is an unrelated reformatting. Such changes must not be included.

2022-01-29 06:11 UTC, webknjaz commented on test/utils/helper.ts
> -
Imports should have two line separator. This change is wrong.

2022-01-29 06:11 UTC, webknjaz commented on test/utils/runCommand.test.ts
> -
Same problem here.