Fix globby import pruned by webpack
ansible/ansible-language-server pull request #293
Opened 2022-04-05 16:31 UTC by tomaciazek

This implements a workaround for globby import being pruned by webpack and subsequently failing client-side.
Fixes #290

2022-04-06 07:18 UTC, ganeshrn approved these changes

2022-04-06 07:20 UTC, ganeshrn commented
Thanks @tomaciazek for fixing the issue.

After the PR is merged will rerun https://github.com/ansible/ansible-language-server/pull/289 to test vscode-ansible test-e2e testcases for unreleased (main branch) of ansible-language-server

2022-04-06 07:51 UTC, ganeshrn requested changes
I am still seeing the issue after following the steps here https://github.com/ansible/ansible-language-server/blob/c9915bf46369b4182e0212599fa7b65c3d2a71eb/.github/workflows/vscode.yml#L36-L48

Also the issue can be  reproduced by following below steps:
1) Running `npm pack` within `ansible-langauge-server`
2)  Installing the generated tar of ansible-language-server in the vscode-ansible repo with
 command `npm install ../ansible-language-server/ansible-ansible-language-server-0.5.4.tgz `
3) Run `npm run webpack`
4) Run `npm run vsce` 
5) Install generated vsix using `code --install-extension ansible-0.8.1.vsix --force`

2022-04-06 19:46 UTC, tomaciazek commented
@ganeshrn Yeah, I totally forgot there is yet another issue with globby: it is calling internal node libraries using modern notation `node:*`, which seems to break with webpack too. There is a workaround for that too, which requires something like this in `vscode-ansible`'s `webpack.config.js`:
```
  externals: [
    function ({ request }, callback) {
      const nodeMatch = request.match(/^node:(.*)$/);
      if (nodeMatch) {
        // Remove the 'node:' prefix
        return callback(null, nodeMatch[1]);
      }
      // Continue without changes
      callback();
    },
    {
      vscode: "commonjs vscode", // the vscode-module is created on-the-fly and must be excluded. Add other modules that cannot be webpack'ed
    },
  ]
```

I tested it following your procedure, and this time it would work...

But I'm starting to agree with you both - maybe this is not the right way. Even though I still think we might hit this kind of issue with some other library (should the maintainers choose to go full ESM), maybe it's enough that we have this backup solution here as a _closed_ (unmerged) PR, and just replace globby with some other tool 😉

2022-04-07 04:41 UTC, priyamsahoo commented
The problem is with the globby compartibility. Right now, to import globby, the code needs to be compiled first (since we have a getGlobby function for it). That's the reason why we don't see any errors while running the extension in dev host mode after we do `npm run compile-withserver`. The problem starts appearing when we make an npm package of the als code.

There could be 2 solutions for it:

1. Find out a way to make dynamic imports work in npm packages. (maybe, it is not supported).
2. Replace globby with some other library that does the work for us.

2022-04-11 17:08 UTC, closed without merging