Fix auto-completion for modules when documentation is not displayed
ansible/ansible-language-server pull request #330
Opened 2022-05-18 17:45 UTC by fredericgiquel

Possible solution for https://github.com/ansible/ansible-language-server/issues/329

It fixes the bug both with VSCodium and Emacs.

2022-05-23 05:34 UTC, priyamsahoo requested changes
Thanks a lot for the fix, @fredericgiquel :)
Everything is fine in the PR, except that the lint job (cspell) in the CI is failing.

The fix for this is to add your username (which you mentioned in the changelog) in `.config/dictionary.txt` under `names and usernames` section in a sorted manner.

2022-05-23 09:17 UTC, ssbarnea commented
@fredericgiquel Have you considered writing a test for it, so we do not accidentally break it in the future?

2022-05-23 12:23 UTC, fredericgiquel commented
@priyamsahoo I added my name in dictionary

@ssbarnea I added tests on newText value for all completion tests (not only modules completion)

2022-05-24 02:39 UTC, priyamsahoo approved these changes

2022-05-24 03:41 UTC, merged